### ISSUE TITLE
OpenSwitch: System is not ready

### ISSUE THREAD

**Issue by wangziyao318** [sfl0r3nz05/OT-NWbasedOnGNS3#1]
<img width="1144" alt="Screenshot 2022-11-17 at 21 46 30" src="https://user-images.githubusercontent.com/69375071/202464242-286ce3cb-0152-4249-aa88-ef42397a00e4.png">

The QEMU OpenSwitch0.4.0 continues to report "System is not ready" upon any config commands. I wait for half an hour and the problem persists.

The OpenSwitch is imported, deployed, and launched without error, and KVM is disabled.

**Comment by wangziyao318** [comment]
My OpenSwitch config in GNS3

<img width="691" alt="Screenshot 2022-11-17 at 22 21 38" src="https://user-images.githubusercontent.com/69375071/202471526-cc962e5e-6c60-4ff5-9c47-47a38e56e2a7.png">

<img width="1223" alt="Screenshot 2022-11-17 at 22 22 13" src="https://user-images.githubusercontent.com/69375071/202471531-a29055ca-f793-439c-8e7e-4415f749cbe2.png">

**Comment by md3anos3s** [comment]
Hi! I found this about the error: 

4.1.2 Cannot Save OpenSwitch Configuration - Error Message - "System is not ready. Please retry after few seconds.."

You must run OpenSwitch with minimum two NICs otherwise system is not ready. In that case, you get an error message - "System is not ready. Please retry after few seconds.."   The comand below starts an OpenSwitch Qemu instance with two NICs attached.

$ /usr/bin/qemu-system-x86_64 -m 2G -enable-kvm OpenSwitch.vdi -serial telnet:localhost:2222,server,nowait  -net nic,id=net0 -device e1000,mac=00:11:22:33:44:00 -net nic,id=net1 -device e1000,mac=00:11:22:33:44:01

I guess you have to change the parameters (the serial flag and the MAC addresses) to adapt it to your network.

Hope it works!

**Comment by wangziyao318** [comment]
Unfortunately it doesn't work.

**Comment by wangziyao318** [comment]
The thing really matters is "-enable-kvm" option, together with 2 NICs installed. Got it worked in my PC with nested virtualization capacity.

<img width="1024" alt="Screenshot 2022-11-26 at 20 19 32" src="https://user-images.githubusercontent.com/69375071/204088647-1f51ce89-f83a-4922-917c-4628d736a1fe.png">
